name: cached_video_player
description: A new flutter plugin that is virtually a clone of official
  video_player plugin except that it supports caching( Android and iOS)
version: 2.1.0
homepage: https://github.com/vikram25897/flutter_cached_video_player

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.lazyarts.vikram.cached_video_player
        pluginClass: CachedVideoPlayerPlugin
      ios:
        pluginClass: CachedVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^6.2.2
  video_player_web: ^2.0.10
  video_player_web_hls: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  pigeon: ^22.4.1
